import pygame

pygame.init()


class WINDOW:
    WIDTH = 600
    HEIGHT = 600
    SIZE = (WIDTH, HEIGHT)
    TITLE = "TIC TAC TOE"


class UPDATE:
    FPS = 60
    PORT = 50019


class COLOURS:
    BLUE = (0, 0, 255)
    RED = (255, 0, 0)
    GREEN = (0, 255, 0)
    BLACK = (0, 0, 0)
    WHITE = (255, 255, 255)
    GREY = (55, 55, 55)

    TRANSPARENT_BACKGROUND = (0, 0, 0, 0)


class GAME_UI:
    USERNAME_LABEL_WIDTH = WINDOW.WIDTH * 0.5
    SCORE_LABEL_WIDTH = WINDOW.WIDTH * 0.3
    LABEL_HEIGHT = WINDOW.HEIGHT * 0.1
    TURN_LABEL_WIDTH = WINDOW.WIDTH

    FONT_SIZE = 20


class LOBBY_UI:
    TITLE_LABEL_WIDTH = WINDOW.WIDTH * 0.75
    TITLE_LABEL_HEIGHT = WINDOW.HEIGHT * 0.1

    CONNECTED_PLAYERS_LABEL_WIDTH = WINDOW.WIDTH * 0.5
    CONNECTED_PLAYERS_LABEL_HEIGHT = TITLE_LABEL_HEIGHT

    START_GAME_BUTTON_WIDTH = WINDOW.WIDTH * 0.25

    TEXT_COLOR = COLOURS.WHITE
    BORDER_COLOR = COLOURS.WHITE
    TITLE_FONT_SIZE = 32
    BUTTON_FONT_SIZE = 20


class BOARD:
    ROWS = 3
    COLS = 3

    SPACING = WINDOW.WIDTH * 0.05
    CELL_WIDTH = WINDOW.WIDTH / COLS - SPACING
    CELL_HEIGHT = (WINDOW.HEIGHT - GAME_UI.LABEL_HEIGHT) / ROWS - SPACING
    LEFT_PADDING = (WINDOW.WIDTH - ROWS * (CELL_WIDTH + SPACING)) / 2

    CELL_NORMAL_COLOR = COLOURS.GREY
    CELL_HOVERED_COLOR = COLOURS.WHITE
    CELL_TEXT_COLOR = COLOURS.BLACK
    X_TEXT_COLOR = COLOURS.RED
    O_TEXT_COLOR = COLOURS.BLUE
    CELL_BORDER_COLOR = COLOURS.BLUE
    CELL_FONT_SIZE = GAME_UI.FONT_SIZE

    CHARS = ["X", "O"]


class UI:
    FONT_NAME = "Consolas"


class MAINMENU_UI:
    # Colors
    TEXT_COLOR = COLOURS.WHITE
    BUTTON_HOVERED_COLOR = (150, 150, 150)
    BUTTON_NORMAL_COLOR = (60, 60, 60)

    # Label Dimensions
    LABEL_WIDTH = WINDOW.WIDTH * 0.8
    LABEL_HEIGHT = LABEL_WIDTH * 0.3
    LABEL_SIZE = LABEL_WIDTH, LABEL_HEIGHT

    # Button Dimensions
    BUTTON_WIDTH = WINDOW.WIDTH * 0.3
    BUTTON_HEIGHT = LABEL_HEIGHT * 0.5
    BUTTON_SIZE = BUTTON_WIDTH, BUTTON_HEIGHT

    # Font Size
    TITLE_LABEL_FONT_SIZE = 32
    BUTTONS_FONT_SIZE = 20
